In [4]:
import pandas as pd

In [15]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv")

In [16]:
# df.total_bedrooms[df.total_bedrooms.isnull()]
df.total_bedrooms.isnull()

0        False
1        False
2        False
3        False
4        False
         ...
20635    False
20636    False
20637    False
20638    False
20639    False
Name: total_bedrooms, Length: 20640, dtype: bool

In [22]:
df.index

RangeIndex(start=0, stop=20640, step=1)

In [5]:
df1 = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")
df1

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [24]:
df1.index

RangeIndex(start=0, stop=9704, step=1)

In [26]:
df1.fuel_type.nunique()

2

In [ ]:
dff = df1[['engine_displacement','num_cylinders','horsepower','vehicle_weight','acceleration','model_year','origin','fuel_type','drivetrain','num_doors','fuel_efficiency_mpg']].count()
# (dff<9704).count()

/tmp/ipykernel_2085/1246205042.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1[dff<9704]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [21]:
df1.engine_displacement[df1.engine_displacement.isnull()]

Series([], Name: engine_displacement, dtype: int64)

In [36]:
df1.count()<9704

engine_displacement    False
num_cylinders           True
horsepower              True
vehicle_weight         False
acceleration            True
model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors               True
fuel_efficiency_mpg    False
dtype: bool

In [40]:
df1[['model_year', 'horsepower','fuel_type']]
df1.head(n=1)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729

In [47]:
df1.index

RangeIndex(start=0, stop=9704, step=1)

In [50]:
df1[df1['num_cylinders'] >= 7]

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg,id
6,240,7.0,127.0,3006.542287,22.2,2012,USA,Gasoline,Front-wheel drive,1.0,13.210412,[ 0 1 2 ... 9701 9702 9703]
26,180,8.0,160.0,3080.170162,10.6,2002,USA,Diesel,All-wheel drive,2.0,15.089880,[ 0 1 2 ... 9701 9702 9703]
49,140,7.0,99.0,3602.664483,17.0,2015,Europe,Gasoline,All-wheel drive,1.0,11.257268,[ 0 1 2 ... 9701 9702 9703]
53,290,7.0,151.0,3715.097082,8.9,2004,Europe,Diesel,All-wheel drive,0.0,12.477270,[ 0 1 2 ... 9701 9702 9703]
58,230,8.0,103.0,2496.548659,16.7,2019,USA,Gasoline,All-wheel drive,0.0,16.667140,[ 0 1 2 ... 9701 9702 9703]
...,...,...,...,...,...,...,...,...,...,...,...,...
9671,170,7.0,190.0,2649.997604,13.9,2009,Asia,Gasoline,All-wheel drive,-1.0,17.264393,[ 0 1 2 ... 9701 9702 9703]
9673,210,7.0,122.0,2322.922345,14.7,2016,Europe,Diesel,All-wheel drive,2.0,17.931718,[ 0 1 2 ... 9701 9702 9703]
9681,210,8.0,181.0,2707.090511,14.8,2007,USA,Diesel,Front-wheel drive,0.0,16.161540,[ 0 1 2 ... 9701 9702 9703]
9682,130,7.0,175.0,3278.454482,13.0,2004,USA,Diesel,Front-wheel drive,0.0,13.729558,[ 0 1 2 ... 9701 9702 9703]
9696,190,7.0,69.0,3133.329210,16.6,2008,Europe,Gasoline,All-wheel drive,1.0,13.418128,[ 0 1 2 ... 9701 9702 9703]

In [3]:
# Q1
import pandas as pd
pd.__version__

'2.3.1'

In [4]:
# Q2
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")
df.index

RangeIndex(start=0, stop=9704, step=1)

In [5]:
# Q3
df.fuel_type.nunique()

2

In [ ]:
# Q4
(df.count() < 9704).sum() # 4 [num_cylinders, horsepower, acceleration, num_doors]

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [7]:
# Q5
df['fuel_efficiency_mpg'][df['origin'].str.lower() == 'asia'].max().round(2)

np.float64(23.76)

In [9]:
# Q6
df['horsepower'].median()

np.float64(149.0)

In [12]:
counter = int(df['horsepower'].count())
counter

8996

In [51]:
series = df.horsepower.values
print(series)
counter = int(df['horsepower'].nunique())
max_freq = 1
most_frequent_num = series[0]
for i in range(counter):
    x = series[0]
    x_freq = series[series == x].shape[0]
    print(f"{x} , {x_freq}")
    if x_freq >= max_freq:
        most_frequent_num = x
        max_freq = x_freq
    series = series[series != x]

print(f"max frequency = {max_freq} and most frequent number is: {most_frequent_num}")
# x = series[0]
# series = series[series != x]
# series[0]

[159.  97.  78. ... 138. 177. 140.]
159.0 , 126
97.0 , 27
78.0 , 8
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
nan , 0
max frequency = 126 and most frequent number is: 159.0

In [48]:
series[series == 78.0].shape[0]

0